name: functional-tests

on:
  # we use pull_request_target to run the CI also for forks
  pull_request_target:
    types: [opened, reopened, synchronize, labeled]
  push:
    branches: [main]

jobs:
  # workflow that is invoked when for PRs with labels 'enable-functional-tests'
  functional-tests-pr:
    name: Functional Tests - PR
    if: contains(github.event.pull_request.labels.*.name, 'enable-functional-tests')
    uses: ./.github/workflows/functional-tests-workflow.yml
    secrets: inherit
    strategy:
      matrix:
        aws-region: ['us-east-1', 'eu-central-1']
    permissions:
      id-token: write
      contents: read
    with:
      # this allows to pick the branch from the PR
      checkout-ref: ${{ github.event.pull_request.head.ref }}
      # this allows to work on fork
      checkout-repository: ${{ github.event.pull_request.head.repo.full_name }}
      aws-region: ${{ matrix.aws-region }}
      concurrency-group: functional_tests_pr_${{ matrix.aws-region }}

  # workflow that is invoked when a push to main happens
  functional-tests-main:
    name: Functional Tests - main
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    uses: ./.github/workflows/functional-tests-workflow.yml
    secrets: inherit
    strategy:
      matrix:
        aws-region: ['us-east-1', 'eu-central-1']
    permissions:
      id-token: write
      contents: read
    with:
      checkout-ref: ${{ github.ref }}
      checkout-repository: ${{ github.repository }}
      aws-region: ${{ matrix.aws-region }}
      concurrency-group: functional_tests_main_${{ matrix.aws-region }}
