# reusable workflow to be called from the main workflow
name: functional-tests-workflow
run-name: "${{ (contains(github.event_name, 'workflow_') && inputs.name) || github.event_name }}: ${{ (contains(github.event_name, 'workflow_') &&  inputs.adapter_branch) || github.ref_name }} by @${{ github.actor }}"

on:
  workflow_call:
    inputs:
      checkout-ref:
        required: true
        type: string
concurrency:
  group: ${{ github.workflow }}-${{ github.event_name }}-${{ contains(github.event_name, 'pull_request') && github.event.pull_request.head.ref || github.sha }}
  cancel-in-progress: true

env:
  DBT_TEST_ATHENA_DATABASE: awsdatacatalog
  DBT_TEST_ATHENA_SCHEMA: dbt-tests
  DBT_TEST_ATHENA_WORK_GROUP: athena-dbt-tests
  DBT_TEST_ATHENA_THREADS: 16
  DBT_TEST_ATHENA_POLL_INTERVAL: 0.5
  DBT_TEST_ATHENA_NUM_RETRIES: 3

jobs:
  functional-tests:
    name: Functional Tests
    runs-on: ubuntu-latest
    env:
      DBT_TEST_ATHENA_S3_STAGING_DIR: ${{ vars.DBT_TEST_ATHENA_S3_BUCKET }}/staging/
      DBT_TEST_ATHENA_S3_TMP_TABLE_DIR: ${{ vars.DBT_TEST_ATHENA_S3_BUCKET }}/tmp_tables/
      DBT_TEST_ATHENA_REGION_NAME: ${{ vars.DBT_TEST_ATHENA_REGION_NAME }}
    steps:
      - name: "Checkout repo"
        uses: actions/checkout@v3
        with:
          ref: ${{ inputs.checkout-ref }}

      - name: "Setup `hatch`"
        uses: dbt-labs/dbt-adapters/.github/actions/setup-hatch@main
        with:
          python-version: ${{ matrix.python-version }}

      - name: "Configure AWS credentials from Test account"
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: arn:aws:iam::${{ secrets.AWS_ACCOUNT_ID }}:role/${{ secrets.ASSUMABLE_ROLE_NAME }}
          aws-region: ${{ vars.DBT_TEST_ATHENA_REGION_NAME }}

      - name: "Functional Test"
        run: hatch run integration-tests
        working-directory: ./dbt-athena
