# reusable workflow to be called from the main workflow
name: functional-tests-workflow

on:
  workflow_call:
    inputs:
      checkout-ref:
        required: true
        type: string
      checkout-repository:
        required: true
        type: string
      aws-region:
        required: true
        type: string

env:
  DBT_TEST_ATHENA_DATABASE: awsdatacatalog
  DBT_TEST_ATHENA_SCHEMA: dbt-tests
  DBT_TEST_ATHENA_WORK_GROUP: athena-dbt-tests
  DBT_TEST_ATHENA_THREADS: 16
  DBT_TEST_ATHENA_POLL_INTERVAL: 0.5

jobs:
  functional-tests:
    name: Functional Tests
    runs-on: ubuntu-latest
    env:
      DBT_TEST_ATHENA_S3_STAGING_DIR: s3://dbt-athena-query-results-${{ inputs.aws-region }}/staging/
      DBT_TEST_ATHENA_S3_TMP_TABLE_DIR: s3://dbt-athena-query-results-${{ inputs.aws-region }}/tmp_tables/
      DBT_TEST_ATHENA_REGION_NAME: ${{ inputs.aws-region }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: ${{ inputs.checkout-ref }}
          repository: ${{ inputs.checkout-repository }}
      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Install dependencies
        run: |
          make install_deps
      - name: Configure AWS credentials from Test account
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: arn:aws:iam::${{ secrets.AWS_ACCOUNT_ID }}:role/${{ secrets.ASSUMABLE_ROLE_NAME }}
          aws-region: ${{ inputs.aws-region }}
      - name: Functional Test
        run: |
          pytest -n 8 tests/functional
